# Generated by Django 6.0.6 on 2026-06-05 09:34

import apps.analysis.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public identifier — safe to expose in URLs.', primary_key=True, serialize=False)),
                ('original_filename', models.CharField(help_text='The filename as the user uploaded it.', max_length=255)),
                ('file', models.FileField(help_text='The uploaded file, stored under a UUID-namespaced path.', upload_to=apps.analysis.models.dataset_upload_path)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploaded', help_text='Current processing state of this dataset.', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Populated when status=failed. Empty otherwise.')),
                ('row_count', models.PositiveIntegerField(blank=True, help_text='Populated after successful processing.', null=True)),
                ('column_count', models.PositiveIntegerField(blank=True, help_text='Populated after successful processing.', null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, help_text='Size of the uploaded file in bytes.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ['-created_at'],
            },
        ),
    ]
